### ISSUE TITLE
Refactor "RideShare" to "RideForce"

### ISSUE THREAD

**Issue by DailyDataMiner** [revaturelabs/rideshare-gateway-service#26]
Currently, when you use "mvn package" it will create "rideshare-zuul.jar"

Pipeline will build properly, but if refactored, you must change build on Jenkins to reflect the name change in the Execute Shell part in the Configuration. Inform pipeline to change that & the Dockerfile.

**Comment by ianprime0509** [comment]
The most recent merge to master fixed this (or maybe it was an earlier merge; I'm not sure).
